PLANT_CATEGORY_INDOOR = "indoor"
PLANT_CATEGORY_OUTDOOR = "outdoor"
PLANT_CATEGORY_FLOWERING = "flowering"
PLANT_CATEGORY_ORNAMENTAL = "ornamental"
PLANT_CATEGORY_FRUIT = "fruit"
PLANT_CATEGORY_HERB = "herb"
PLANT_CATEGORY_OTHER = "other"


PLANT_CATEGORIES = (
    (PLANT_CATEGORY_INDOOR, "Indoor"),
    (PLANT_CATEGORY_OUTDOOR, "Outdoor"),
    (PLANT_CATEGORY_FLOWERING, "Flowering"),
    (PLANT_CATEGORY_ORNAMENTAL, "Ornamental"),
    (PLANT_CATEGORY_FRUIT, "Fruit"),
    (PLANT_CATEGORY_HERB, "Herb"),
    (PLANT_CATEGORY_OTHER, "Other"),
)



PLANT_IMAGE_TYPE_MAIN = "main"
PLANT_IMAGE_TYPE_SUB = "sub"

PLANT_IMAGE_TYPES = (
    (PLANT_IMAGE_TYPE_MAIN, "Main"),
    (PLANT_IMAGE_TYPE_SUB, "Sub"),
)