# Generated by Django 5.2.17 on 2026-09-25 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0002_plantimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='plants.plant')),
            ],
            options={
                'db_table': 'inventory',
                'ordering': ['-created_at'],
            },
        ),
    ]
