# Generated by Django 5.2.17 on 2026-09-25 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_before', models.PositiveIntegerField()),
                ('quantity', models.IntegerField()),
                ('quantity_after', models.PositiveIntegerField()),
                ('movement_type', models.CharField(choices=[('RESTOCK', 'Restock'), ('SALE', 'Sale'), ('RETURN', 'Return'), ('ADJUSTMENT', 'Adjustment'), ('DAMAGE', 'Damage'), ('EXPIRED', 'Expired')], max_length=20)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.inventory')),
            ],
            options={
                'db_table': 'stock_movement',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['inventory', '-created_at'], name='stock_movem_invento_81bd02_idx'), models.Index(fields=['movement_type', '-created_at'], name='stock_movem_movemen_485d19_idx')],
            },
        ),
    ]
