# Generated by Django 5.2.17 on 2026-09-17 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='plants/')),
                ('image_type', models.CharField(choices=[('main', 'Main'), ('sub', 'Sub')], default='sub', max_length=10)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='plants.plant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('image_type', 'main')), fields=('plant',), name='unique_main_image_per_plant')],
            },
        ),
    ]
